version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: moab
      POSTGRES_DB:  movies
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: lionmd76@gmail.com
      PGADMIN_DEFAULT_PASSWORD: example
    volumes:
      - pgadm:/var/lib/pgadmin
    ports:
      - 9090:80


volumes:
  pg-data:
  pgadm: